In [1]:
import cv2
import numpy as np

In [2]:
img1 = np.zeros((512, 512, 3), np.uint8)
windowName = 'OpenCv BGR Color Palette'

In [3]:
def emptyfun():
    pass

In [4]:
arr = np.zeros((2, 2, 2), np.uint8)
print(arr)
print("==========")
arr[ : ] = [1, 2]
print(arr)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]


In [5]:
cv2.namedWindow(windowName)
cv2.createTrackbar('B', windowName, 0, 255, emptyfun)
cv2.createTrackbar('G', windowName, 0, 255, emptyfun)
cv2.createTrackbar('R', windowName, 0, 255, emptyfun)
while(1):
    cv2.imshow(windowName, img1)
    ## 27 is the code for esc key
    if(cv2.waitKey(1) == 27): 
        break
    blue = cv2.getTrackbarPos('B', windowName)
    green = cv2.getTrackbarPos('G', windowName)
    red = cv2.getTrackbarPos('R', windowName)
    img1[:] = [blue, green, red]
    

cv2.destroyAllWindows()

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given

TypeError: emptyfun() takes 0 positional arguments but 1 was given